# Generated by Django 4.0.4 on 2022-04-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(default='exit', max_length=50),
            preserve_default=False,
        ),
    ]
